export interface EvidenceData {
  id: string;
  sha: string;
  message: string;
  timestamp: string;
  correlationStrength: "High" | "Medium" | "Low";
  details: string;
  filePath?: string;
}

export interface TimelineData {
  id: string;
  timestamp: string;
  event: string;
  description: string;
  category: "dependency" | "trigger" | "failure" | "mitigation";
}

export interface RecommendationData {
  id: string;
  title: string;
  impact: "High" | "Medium" | "Low";
  description: string;
}

export interface MockInvestigationReport {
  repository: string;
  branch: string;
  rootCause: {
    trigger: string;
    description: string;
    impact: string;
    confidence: number;
  };
  summary: string;
  evidence: EvidenceData[];
  timeline: TimelineData[];
  recommendations: RecommendationData[];
}

export const MOCK_INVESTIGATION_REPORT: MockInvestigationReport = {
  repository: "stap777/SonD",
  branch: "main",
  rootCause: {
    trigger: "Authlib Dependency Upgrade (1.6.11 → 1.7.2)",
    description: "The incident was triggered by an automatic authentication library upgrade pushed in commit 99a1b1ed. Version 1.7.2 of Authlib introduces strict token header validation parameters that are incompatible with the legacy session token format generated by our client gateway, causing immediate decoding exceptions.",
    impact: "Complete validation failure across all active OAuth user checkouts, blocking gateway routing and downstream session synchronization.",
    confidence: 90
  },
  summary: "The auth-service validation failure was triggered by a routine Authlib library upgrade pushed shortly before the incident. This upgrade introduced strict signature checks that rejected existing user check sessions, throwing unhandled JWT DecodeErrors in the synchronization threads.",
  evidence: [
    {
      id: "ev-1",
      sha: "99a1b1ed",
      message: "Bump authlib from 1.6.11 to 1.7.2",
      timestamp: "2026-05-30 10:48:12 UTC",
      correlationStrength: "High",
      details: "Modified files: requirements.txt, pyproject.toml. Triggered automatic rebuild of auth-service container.",
      filePath: "requirements.txt"
    },
    {
      id: "ev-2",
      sha: "f1a23b4e",
      message: "gateway: Refactor session decoding block to use standard headers",
      timestamp: "2026-05-30 10:49:05 UTC",
      correlationStrength: "Medium",
      details: "Renders payload mismatch checks. gateway auth validation subroutines returned 500 Server Error.",
      filePath: "src/gateway/decoder.py"
    },
    {
      id: "ev-3",
      sha: "c9d8e7f6",
      message: "deployment: Rollout new gateway container tags",
      timestamp: "2026-05-30 10:49:40 UTC",
      correlationStrength: "High",
      details: "Check suites failed on status checks. CI pipeline blocked for main deployment check.",
      filePath: "deploy/kubernetes/gateway.yaml"
    }
  ],
  timeline: [
    {
      id: "tl-1",
      timestamp: "10:48 UTC",
      event: "Dependency Updated",
      description: "Automatic bot dependency upgrade bumped authlib 1.6.11 → 1.7.2 in requirements.txt (commit 99a1b1ed).",
      category: "dependency"
    },
    {
      id: "tl-2",
      timestamp: "10:49 UTC",
      event: "Incident Triggered",
      description: "Health probe check failed on gateway auth-service. First JWT decoding exceptions registered in session filters.",
      category: "trigger"
    },
    {
      id: "tl-3",
      timestamp: "10:49 UTC",
      event: "Service Failure",
      description: "Auth-service container entered crashback loop. Gateway checkout validation transactions collapsed (100% failure rate).",
      category: "failure"
    }
  ],
  recommendations: [
    {
      id: "rec-1",
      title: "Revert Authlib Upgrade to 1.6.11",
      impact: "High",
      description: "Immediately rollback the dependency bump in requirements.txt to restore legacy validation compatibility while a patch is prepared."
    },
    {
      id: "rec-2",
      title: "Introduce Signature Validation Fallback",
      impact: "Medium",
      description: "Update the gateway token decoder to handle missing algorithm header parameters gracefully instead of raising unhandled DecodeErrors."
    },
    {
      id: "rec-3",
      title: "Add Session Regression Integration Tests",
      impact: "High",
      description: "Configure continuous integration to run token signature compatibility matrix checks against all supported Authlib libraries."
    }
  ]
};
